feat: Create Offers
holaplex/metaplex-program-library pull request #4
Opened 2022-07-21 05:30 UTC by sunguru98

Create offer instruction is written with CPI instructions to `public_bid` and `deposit`

2022-07-21 08:04 UTC, kespinola requested changes
minor clean recommendations but looks really good. ty.

2022-07-21 08:04 UTC, kespinola commented on listing-rewards/program/tests/create_offer.rs
> +    .unwrap();
auction house doesn't actually make use of wSOL. Its a special condition to trigger the use of sol so you can airdrop directly to the buyer's wallet. To further simplify you can make the context.payer setup by program test as the buyer.

2022-07-21 08:04 UTC, kespinola commented on listing-rewards/program/tests/create_offer.rs
> +    println!("{:?}", tx_response);
drop println

2022-07-21 08:04 UTC, kespinola commented on listing-rewards/program/tests/listing_rewards_test/mod.rs
> +pub const TEST_COLLECTION: &str = "Cehzo7ugAvuYcTst9HF24ackLxnrpDkzHFajj17FuyUR";
Oh test collection is already in the testing module. Drop it from program constants.

2022-07-21 08:08 UTC, sunguru98 commented on listing-rewards/program/src/offers/create_offer/mod.rs
> +    )?;
Actually, I did do the suggested action, however it ended with up an error stating as ProgramFailedToExecute error. Swapping them both fixed that weird error though.

2022-07-21 08:08 UTC, sunguru98 commented on listing-rewards/program/src/constants.rs
> +pub const TEST_COLLECTION: &str = "Cehzo7ugAvuYcTst9HF24ackLxnrpDkzHFajj17FuyUR";
This obv is a blunder haha. Will delete it

2022-07-25 12:28 UTC, kespinola approved these changes

2022-07-25 12:28 UTC, merged